name: Jekyll Build and Deploy with Docker

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Jekyll Site
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/srv/jekyll \
            jekyll/jekyll:latest \
            jekyll build

      # You can add more steps here for additional tasks, such as testing

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
